
; ASM FILE code\gameflow\battle\spellrangehack.asm :
; 0x27D9E..0x27E34 : additional range for spell (and attack ?)

; =============== S U B R O U T I N E =======================================

SpellRange3:    dc.b  $C
                dc.b   0
                dc.b $FD
                dc.b $FF
                dc.b $FE
                dc.b $FE
                dc.b $FF
                dc.b $FD
                dc.b   0
                dc.b $FE
                dc.b   1
                dc.b $FF
                dc.b   2
                dc.b   0
                dc.b   3
                dc.b   1
                dc.b   2
                dc.b   2
                dc.b   1
                dc.b   3
                dc.b   0
                dc.b   2
                dc.b $FF
                dc.b   1
                dc.b $FE
                
SpellRange4:    dc.b $10
                dc.b   0
                dc.b $FC
                dc.b $FF
                dc.b $FD
                dc.b $FE
                dc.b $FE
                dc.b $FD
                dc.b $FF
                dc.b $FC
                dc.b   0
                dc.b $FD
                dc.b   1
                dc.b $FE
                dc.b   2
                dc.b $FF
                dc.b   3
                dc.b   0
                dc.b   4
                dc.b   1
                dc.b   3
                dc.b   2
                dc.b   2
                dc.b   3
                dc.b   1
                dc.b   4
                dc.b   0
                dc.b   3
                dc.b $FF
                dc.b   2
                dc.b $FE
                dc.b   1
                dc.b $FD

SpellRange5:    dc.b $14
                dc.b   0
                dc.b $FB
                dc.b $FF
                dc.b $FC
                dc.b $FE
                dc.b $FD
                dc.b $FD
                dc.b $FE
                dc.b $FC
                dc.b $FF
                dc.b $FB
                dc.b   0
                dc.b $FC
                dc.b   1
                dc.b $FD
                dc.b   2
                dc.b $FE
                dc.b   3
                dc.b $FF
                dc.b   4
                dc.b   0
                dc.b   5
                dc.b   1
                dc.b   4
                dc.b   2
                dc.b   3
                dc.b   3
                dc.b   2
                dc.b   4
                dc.b   1
                dc.b   5
                dc.b   0
                dc.b   4
                dc.b $FF
                dc.b   3
                dc.b $FE
                dc.b   2
                dc.b $FD
                dc.b   1
                dc.b $FC

SpellRange6:    dc.b $18
                dc.b   0
                dc.b $FA
                dc.b $FF
                dc.b $FB
                dc.b $FE
                dc.b $FC
                dc.b $FD
                dc.b $FD
                dc.b $FC
                dc.b $FE
                dc.b $FB
                dc.b $FF
                dc.b $FA
                dc.b   0
                dc.b $FB
                dc.b   1
                dc.b $FC
                dc.b   2
                dc.b $FD
                dc.b   3
                dc.b $FE
                dc.b   4
                dc.b $FF
                dc.b   5
                dc.b   0
                dc.b   6
                dc.b   1
                dc.b   5
                dc.b   2
                dc.b   4
                dc.b   3
                dc.b   3
                dc.b   4
                dc.b   2
                dc.b   5
                dc.b   1
                dc.b   6
                dc.b   0
                dc.b   5
                dc.b $FF
                dc.b   4
                dc.b $FE
                dc.b   3
                dc.b $FD
                dc.b   2
                dc.b $FC
                dc.b   1
                dc.b $FB

SpellRange7:    dc.b $1C
                dc.b   0
                dc.b $F9
                dc.b $FF
                dc.b $FA
                dc.b $FE
                dc.b $FB
                dc.b $FD
                dc.b $FC
                dc.b $FC
                dc.b $FD
                dc.b $FB
                dc.b $FE
                dc.b $FA
                dc.b $FF
                dc.b $F9
                dc.b   0
                dc.b $FA
                dc.b   1
                dc.b $FB
                dc.b   2
                dc.b $FC
                dc.b   3
                dc.b $FD
                dc.b   4
                dc.b $FE
                dc.b   5
                dc.b $FF
                dc.b   6
                dc.b   0
                dc.b   7
                dc.b   1
                dc.b   6
                dc.b   2
                dc.b   5
                dc.b   3
                dc.b   4
                dc.b   4
                dc.b   3
                dc.b   5
                dc.b   2
                dc.b   6
                dc.b   1
                dc.b   7
                dc.b   0
                dc.b   6
                dc.b $FF
                dc.b   5
                dc.b $FE
                dc.b   4
                dc.b $FD
                dc.b   3
                dc.b $FC
                dc.b   2
                dc.b $FB
                dc.b   1
                dc.b $FA
                dc.b $FF

; End of additional range
